export const ACCOUNT = {
  PASSWORD_SETTINGS_INFORMATION: 'PASSWORD_SETTINGS_INFORMATION',
  PASSWORD_SETTINGS_INFORMATION_NEW_PASSWORD:
    'PASSWORD_SETTINGS_INFORMATION_NEW_PASSWORD',
  EDIT_BUTTON_LABEL: 'EDIT_BUTTON_LABEL',
  CONFIGURE_BUTTON_LABEL: 'CONFIGURE_BUTTON_LABEL',
  PASSWORD_WEAK_ERROR: 'PASSWORD_WEAK_ERROR',
  PASSWORD_DO_NOT_MATCH_ERROR: 'PASSWORD_DO_NOT_MATCH_ERROR',
  NEW_PASSWORD_SHOULD_NOT_MATCH_CURRENT_PASSWORD_ERROR:
    'NEW_PASSWORD_SHOULD_NOT_MATCH_CURRENT_PASSWORD_ERROR',
};
