export const ACCOUNT = {
  LOGIN_REQUIRED_TEXT: 'LOGIN_REQUIRED_TEXT',
  LOGIN_REQUIRED_BUTTON_TEXT: 'LOGIN_REQUIRED_BUTTON_TEXT',
  PASSWORD_SETTINGS_INFORMATION: 'PASSWORD_SETTINGS_INFORMATION',
  PASSWORD_SETTINGS_INFORMATION_NEW_PASSWORD:
    'PASSWORD_SETTINGS_INFORMATION_NEW_PASSWORD',
  EDIT_BUTTON_LABEL: 'EDIT_BUTTON_LABEL',
  CONFIGURE_BUTTON_LABEL: 'CONFIGURE_BUTTON_LABEL',
  PASSWORD_WEAK_ERROR: 'PASSWORD_WEAK_ERROR',
  PASSWORD_DO_NOT_MATCH_ERROR: 'PASSWORD_DO_NOT_MATCH_ERROR',
  NEW_PASSWORD_SHOULD_NOT_MATCH_CURRENT_PASSWORD_ERROR:
    'NEW_PASSWORD_SHOULD_NOT_MATCH_CURRENT_PASSWORD_ERROR',
  REQUIRED_FIELD_ERROR: 'REQUIRED_FIELD_ERROR',
  LOGOUT_BUTTON: 'LOGOUT_BUTTON',
  LOG_IN_BUTTON: 'LOG_IN_BUTTON',
  REGISTER_BUTTON: 'REGISTER_BUTTON',
  HERE_BUTTON: 'HERE_BUTTON',
  TEMPORARY_MOVED_ACCOUNT_HOME_PAGE_MESSAGE:
    'TEMPORARY_MOVED_ACCOUNT_HOME_PAGE_MESSAGE',
};
